"""
Data quality / churn-signal summary — Use Case 4

Reads the processed CSVs (must run etl.py first) and writes a short
markdown report that Backend, Churn ML, and Sales ML can all read before
building on top of this data.

Run from the repo root, after etl.py:
    python data/etl/data_quality_report.py
"""

import os
import pandas as pd

PROCESSED_DIR = os.path.join("data", "processed")
REPORT_PATH = os.path.join("docs", "DATA_QUALITY_SUMMARY.md")


def load_processed():
    paths = {
        "customers": os.path.join(PROCESSED_DIR, "customers.csv"),
        "products": os.path.join(PROCESSED_DIR, "products.csv"),
        "orders": os.path.join(PROCESSED_DIR, "orders.csv"),
    }
    missing = [name for name, p in paths.items() if not os.path.exists(p)]
    if missing:
        print(f"ERROR: missing processed file(s) for {missing}. Run etl.py first.")
        raise SystemExit(1)

    return (
        pd.read_csv(paths["customers"], parse_dates=["signup_date"]),
        pd.read_csv(paths["products"]),
        pd.read_csv(paths["orders"], parse_dates=["order_date"]),
    )


def build_report(customers: pd.DataFrame, products: pd.DataFrame, orders: pd.DataFrame) -> str:
    lines = []
    lines.append("# Data Quality & Churn Signal Summary")
    lines.append("")
    lines.append("Generated by `data/etl/data_quality_report.py` from `data/processed/`. "
                  "Regenerate after any ETL change — do not hand-edit this file.")
    lines.append("")

    # --- Row counts & nulls ---
    lines.append("## Row counts")
    lines.append(f"- customers: {len(customers)}")
    lines.append(f"- products: {len(products)}")
    lines.append(f"- orders: {len(orders)}")
    lines.append("")

    lines.append("## Null checks")
    for name, df in [("customers", customers), ("products", products), ("orders", orders)]:
        null_cols = df.columns[df.isnull().any()].tolist()
        if null_cols:
            lines.append(f"- **{name}**: nulls found in {null_cols}")
        else:
            lines.append(f"- **{name}**: no nulls")
    lines.append("")

    # --- Churn signal: subscription_status ---
    lines.append("## Subscription status (churn label candidate)")
    status_counts = customers["subscription_status"].value_counts()
    status_pct = (status_counts / len(customers) * 100).round(1)
    for status in status_counts.index:
        lines.append(f"- {status}: {status_counts[status]} ({status_pct[status]}%)")
    lines.append("")
    lines.append("> Suggested churn label for modeling: `cancelled` = churned, "
                  "`paused` = at-risk, `active` = retained. Confirm this mapping "
                  "with the churn-ml branch before training.")
    lines.append("")

    # --- Cancellations distribution ---
    lines.append("## Cancellations count distribution")
    desc = customers["cancellations_count"].describe()
    lines.append(f"- min: {desc['min']:.0f}, max: {desc['max']:.0f}, "
                  f"mean: {desc['mean']:.2f}, median: {customers['cancellations_count'].median():.0f}")
    lines.append("")

    # --- Ratings ---
    lines.append("## Customer ratings")
    rdesc = customers["rating"].describe()
    lines.append(f"- min: {rdesc['min']:.1f}, max: {rdesc['max']:.1f}, mean: {rdesc['mean']:.2f}")
    lines.append("")

    # --- Country / gender breakdown ---
    lines.append("## Country breakdown")
    for country, count in customers["country"].value_counts().items():
        lines.append(f"- {country}: {count}")
    lines.append("")

    lines.append("## Gender breakdown")
    for gender, count in customers["gender"].value_counts().items():
        lines.append(f"- {gender}: {count}")
    lines.append("")

    # --- Category / revenue for sales-ml ---
    lines.append("## Category order volume & revenue (sales-forecasting signal)")
    merged = orders.merge(products[["product_id", "category"]], on="product_id", how="left")
    cat_summary = merged.groupby("category").agg(
        orders=("order_id", "count"),
        total_revenue=("line_total", "sum"),
    ).round(2).sort_values("total_revenue", ascending=False)
    for cat, row in cat_summary.iterrows():
        lines.append(f"- {cat}: {int(row['orders'])} orders, ${row['total_revenue']:,.2f} revenue")
    lines.append("")

    # --- Date range ---
    lines.append("## Date ranges")
    lines.append(f"- signup_date: {customers['signup_date'].min().date()} to {customers['signup_date'].max().date()}")
    lines.append(f"- order_date: {orders['order_date'].min().date()} to {orders['order_date'].max().date()}")
    lines.append("")
    lines.append("> Note: this dataset has exactly one order per customer (no repeat "
                  "purchase history), so `purchase_frequency` is a self-reported count, "
                  "not derivable from multiple order rows. Sales/demand forecasting "
                  "should treat this as a snapshot dataset, not a time series of "
                  "individual transactions.")

    return "\n".join(lines)


def main():
    customers, products, orders = load_processed()
    report = build_report(customers, products, orders)

    os.makedirs("docs", exist_ok=True)
    with open(REPORT_PATH, "w", encoding="utf-8") as f:
        f.write(report)

    print(f"Report written to {REPORT_PATH}")


if __name__ == "__main__":
    main()