/**
 * Seed script — loads data/processed/*.csv (generated by data/etl/etl.py)
 * into Postgres.
 *
 * Churn predictions: reads ml/churn/output/predictions.csv if present
 * (source = 'model'); falls back to a heuristic mock (source = 'mock')
 * if the real model hasn't been run yet. Same pattern for sales
 * forecasts once feature/sales-ml lands.
 *
 * Run from the backend/ folder:
 *   npm run seed
 */

import fs from "fs";
import path from "path";
import { Pool } from "pg";
import dotenv from "dotenv";

dotenv.config();

const pool = new Pool({ connectionString: process.env.DATABASE_URL });

const PROCESSED_DIR = path.join(__dirname, "..", "..", "..", "data", "processed");
const CHURN_PREDICTIONS_PATH = path.join(__dirname, "..", "..", "..", "ml", "churn", "output", "predictions.csv");

interface Customer {
  customer_id: string;
  age: number;
  gender: string;
  country: string;
  signup_date: string;
  subscription_status: string;
  cancellations_count: number;
  purchase_frequency: number;
  rating: number;
}

interface Product {
  product_id: string;
  product_name: string;
  category: string;
  unit_price: number;
}

interface Order {
  order_id: string;
  customer_id: string;
  product_id: string;
  order_date: string;
  quantity: number;
  unit_price: number;
  line_total: number;
}

interface ChurnPredictionRow {
  customer_id: string;
  churn_probability: string;
  risk_tier: string;
  top_factor: string;
}

/** Minimal CSV parser — fine for this dataset (no embedded commas/quotes). */
function parseCsv<T>(filePath: string): T[] {
  const content = fs.readFileSync(filePath, "utf-8").trim();
  const [headerLine, ...lines] = content.split(/\r?\n/);
  const headers = headerLine.split(",");

  return lines.map((line) => {
    const values = line.split(",");
    const row: Record<string, string> = {};
    headers.forEach((h, i) => {
      row[h] = values[i];
    });
    return row as unknown as T;
  });
}

function requireProcessedFile(name: string): string {
  const filePath = path.join(PROCESSED_DIR, name);
  if (!fs.existsSync(filePath)) {
    console.error(`ERROR: ${filePath} not found.`);
    console.error("Run 'python data/etl/etl.py' from the repo root first.");
    process.exit(1);
  }
  return filePath;
}

/** Heuristic mock churn prediction — used only if the real model CSV isn't present. */
function mockChurnPrediction(c: Customer): {
  churn_probability: number;
  risk_tier: string;
  top_factor: string;
} {
  let base = 0.1;
  let topFactor = "stable subscription";

  if (c.subscription_status === "cancelled") {
    base = 0.85;
    topFactor = "subscription already cancelled";
  } else if (c.subscription_status === "paused") {
    base = 0.5;
    topFactor = "subscription paused";
  }

  const cancellationBoost = Math.min(c.cancellations_count * 0.05, 0.15);
  const lowFrequencyBoost = c.purchase_frequency < 10 ? 0.1 : 0;

  let probability = Math.min(base + cancellationBoost + lowFrequencyBoost, 0.98);
  probability = Math.round(probability * 10000) / 10000;

  if (cancellationBoost >= 0.15 && c.subscription_status === "active") {
    topFactor = "high cancellation history";
  } else if (lowFrequencyBoost > 0 && c.subscription_status === "active") {
    topFactor = "low purchase frequency";
  }

  let riskTier: string;
  if (probability >= 0.75) riskTier = "critical";
  else if (probability >= 0.5) riskTier = "high";
  else if (probability >= 0.25) riskTier = "medium";
  else riskTier = "low";

  return { churn_probability: probability, risk_tier: riskTier, top_factor: topFactor };
}

async function seedCustomers(client: import("pg").PoolClient) {
  const file = requireProcessedFile("customers.csv");
  const customers = parseCsv<Customer>(file);

  for (const c of customers) {
    await client.query(
      `INSERT INTO customers
        (customer_id, age, gender, country, signup_date, subscription_status,
         cancellations_count, purchase_frequency, rating)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)`,
      [
        c.customer_id,
        Number(c.age),
        c.gender,
        c.country,
        c.signup_date,
        c.subscription_status,
        Number(c.cancellations_count),
        Number(c.purchase_frequency),
        Number(c.rating),
      ]
    );
  }
  console.log(`Seeded ${customers.length} customers.`);
  return customers;
}

async function seedProducts(client: import("pg").PoolClient) {
  const file = requireProcessedFile("products.csv");
  const products = parseCsv<Product>(file);

  for (const p of products) {
    await client.query(
      `INSERT INTO products (product_id, product_name, category, unit_price)
       VALUES ($1, $2, $3, $4)`,
      [p.product_id, p.product_name, p.category, Number(p.unit_price)]
    );
  }
  console.log(`Seeded ${products.length} products.`);
}

async function seedOrders(client: import("pg").PoolClient) {
  const file = requireProcessedFile("orders.csv");
  const orders = parseCsv<Order>(file);

  for (const o of orders) {
    await client.query(
      `INSERT INTO orders (order_id, customer_id, product_id, order_date, quantity, unit_price, line_total)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [
        o.order_id,
        o.customer_id,
        o.product_id,
        o.order_date,
        Number(o.quantity),
        Number(o.unit_price),
        Number(o.line_total),
      ]
    );
  }
  console.log(`Seeded ${orders.length} orders.`);
}

/**
 * Churn predictions — CSV-or-mock fallback pattern.
 * If ml/churn/output/predictions.csv exists (real model ran), use it
 * with source='model'. Otherwise generate the heuristic mock with
 * source='mock'.
 */
async function seedChurnPredictions(client: import("pg").PoolClient, customers: Customer[]) {
  if (fs.existsSync(CHURN_PREDICTIONS_PATH)) {
    console.log("Real churn predictions.csv found — using model output (source: model).");
    const rows = parseCsv<ChurnPredictionRow>(CHURN_PREDICTIONS_PATH);

    const customerIds = new Set(customers.map((c) => c.customer_id));
    let skipped = 0;

    for (const row of rows) {
      if (!customerIds.has(row.customer_id)) {
        skipped++;
        continue;
      }
      await client.query(
        `INSERT INTO churn_predictions (customer_id, churn_probability, risk_tier, top_factor, source)
         VALUES ($1, $2, $3, $4, 'model')`,
        [row.customer_id, Number(row.churn_probability), row.risk_tier, row.top_factor]
      );
    }

    if (skipped > 0) {
      console.warn(`WARNING: ${skipped} row(s) in predictions.csv referenced unknown customer_id, skipped.`);
    }
    console.log(`Seeded ${rows.length - skipped} real churn predictions (source: model).`);
  } else {
    console.log("No predictions.csv found — falling back to mock churn predictions (source: mock).");
    for (const c of customers) {
      const { churn_probability, risk_tier, top_factor } = mockChurnPrediction(c);
      await client.query(
        `INSERT INTO churn_predictions (customer_id, churn_probability, risk_tier, top_factor, source)
         VALUES ($1, $2, $3, $4, 'mock')`,
        [c.customer_id, churn_probability, risk_tier, top_factor]
      );
    }
    console.log(`Seeded ${customers.length} mock churn predictions (source: mock).`);
  }
}

async function seedMockSalesForecasts(client: import("pg").PoolClient) {
  const file = requireProcessedFile("products.csv");
  const products = parseCsv<Product>(file);

  // Still mock — feature/sales-ml hasn't merged yet. Same CSV-or-mock
  // pattern will apply here once ml/sales-demand/output/forecast.csv exists.
  for (const p of products.slice(0, 50)) {
    const predictedUnits = Math.round(20 + Math.random() * 80);
    const predictedRevenue = Math.round(predictedUnits * p.unit_price * 100) / 100;

    await client.query(
      `INSERT INTO sales_forecasts (product_name, period, predicted_units, predicted_revenue, source)
       VALUES ($1, $2, $3, $4, 'mock')`,
      [p.product_name, "next_quarter", predictedUnits, predictedRevenue]
    );
  }
  console.log(`Seeded mock sales forecasts for 50 products (source: mock).`);
}

async function main() {
  const client = await pool.connect();
  try {
    console.log("Clearing existing data...");
    await client.query("TRUNCATE sales_forecasts, churn_predictions, orders, products, customers RESTART IDENTITY CASCADE;");

    await client.query("BEGIN");
    const customers = await seedCustomers(client);
    await seedProducts(client);
    await seedOrders(client);
    await seedChurnPredictions(client, customers);
    await seedMockSalesForecasts(client);
    await client.query("COMMIT");

    console.log("Seed complete.");
  } catch (err) {
    await client.query("ROLLBACK");
    console.error("Seed failed, rolled back:", err);
    process.exit(1);
  } finally {
    client.release();
    await pool.end();
  }
}

main();